### ISSUE TITLE
When are attribute callbacks invoked?

### ISSUE THREAD

**Issue by jdinan** [mpi-forum/mpi-issues#30] opened 2015-12-10 00:42 UTC
### Issue Summary

In the context of MPI_Comm_idup, MPI does not specify when attribute copy callbacks are invoked.
### Proposed Fix

Attribute callbacks should be called before the communicator duplication routine returns.

(this is a placeholder for future expansion)

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2015-12-10 05:49
References from trac

Trac ticket 304: Fix the attribute disaster
https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/304

Trac ticket 71: Specify order of attribute delete callbacks on MPI_COMM_SELF at MPI_FINALIZE
https://svn.mpi-forum.org/trac/mpi-forum-web/ticket/71

Trac ticket 374: clarify attribute destructor semantics
svn.mpi-forum.org/trac/mpi-forum-web/ticket/374

**Comment by pavanbalaji** [comment] 2015-12-10 22:32
The issue is not specific to `MPI_COMM_IDUP` and exists with `MPI_COMM_DUP` as well.  For example, the debate at the Forum was whether it was valid for an MPI implementation to invoke the callbacks on first use of the communicator.

**Comment by schulzm** [comment] 2018-06-13 22:40
Dan found an old email conversation that concluded that this hard, if not impossible, to cleanly define - closing the ticket

**Closed by schulzm** 2018-06-13 22:40 UTC
Labels: not ready, wg-collectives
