### ISSUE TITLE
Fortran interface: Update references from TS29113 to Fortran 2018

### ISSUE THREAD

**Issue by reinh-bader** [mpi-forum/mpi-issues#521] opened 2021-09-30 13:34 UTC
# Problem

The MPI standard - for the purpose of defining the modern Fortran interfaces - in many places refers to ISO/IEC TS 29113.
This TS has been retired already some time ago, i.e. formally it is not a valid specification document any more.
This is because all its technical content was subsumed into the Fortran 2018 standard (and indeed some additional corrections
were applied during the integration process).
 
# Proposal

Change references to "Fortran 2018 or later" in future releases of the MPI document.

# Changes to the Text

TBD. 

# Impact on Implementations

This should not have impact on implementation, but is mostly editorial work.

# Impact on Users

Better readability of the document.

# References and Pull Requests

None known.

**Comment by wesbland** [comment] 2022-07-20 16:14
Duplicate of https://github.com/mpi-forum/mpi-issues/issues/163

If that issue seems insufficient, please let us know.

**Closed as not planned by wesbland** 2022-07-20 16:14 UTC
Labels: wg-fortran, [done] mpi-4.1
