### ISSUE TITLE
Language Bindings Summary Chapter RC Review

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#364] opened 2020-12-02 14:09 UTC
# Problem

Comments from @artpol84:

> Please note, that I’m not familiar with Fortran bindings and mostly was using a common sense and comparing with the MPI v3 standard. So I was marking things that caught my eye, but I don’t think they are actually issues. It seems that autogeneration works pretty well.
 
Comments:
1. Each function appears twice. There is a slight difference between the 2 definitions.
One of them is equal to MPIv3, another is of (KIND=MPI_COUNT_KIND).
I assume this is leveraging Fortran function overloading.
I think that there should be a comment at the beginning of the A4 section explaining why we have 2 bindings for some of the functions.
 
Example:
```
MPI_Rget(origin_addr, origin_count, origin_datatype, target_rank,
target_disp, target_count, target_datatype, win, request,
ierror)
TYPE(*), DIMENSION(..), ASYNCHRONOUS :: origin_addr
INTEGER(KIND=MPI_COUNT_KIND), INTENT(IN) :: origin_count, target_count
TYPE(MPI_Datatype), INTENT(IN) :: origin_datatype, target_datatype
INTEGER, INTENT(IN) :: target_rank
INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: target_disp
TYPE(MPI_Win), INTENT(IN) :: win
TYPE(MPI_Request), INTENT(OUT) :: request
INTEGER, OPTIONAL, INTENT(OUT) :: ierror
 
MPI_Rget(origin_addr, origin_count, origin_datatype, target_rank,
target_disp, target_count, target_datatype, win, request,
ierror)
TYPE(*), DIMENSION(..), ASYNCHRONOUS :: origin_addr
INTEGER, INTENT(IN) :: origin_count, target_rank, target_count
TYPE(MPI_Datatype), INTENT(IN) :: origin_datatype, target_datatype
INTEGER(KIND=MPI_ADDRESS_KIND), INTENT(IN) :: target_disp
TYPE(MPI_Win), INTENT(IN) :: win
TYPE(MPI_Request), INTENT(OUT) :: request
INTEGER, OPTIONAL, INTENT(OUT) :: ierror
```
* [x] not a problem, see comments below
 
2. In MPIv3 all the MPI functions/datatypes are links to the definitions.
It is lost in v4rc.

* [x] repeated as open issue in #405 
 
3. No INTENT info for the status / No ASYNCHRONOUS/INTENT(IN) for the buf (same in MPIv3):
```
MPI_File_read(fh, buf, count, datatype, status, ierror)
TYPE(MPI_File), INTENT(IN) :: fh
TYPE(*), DIMENSION(..) :: buf
INTEGER(KIND=MPI_COUNT_KIND), INTENT(IN) :: count
TYPE(MPI_Datatype), INTENT(IN) :: datatype
TYPE(MPI_Status) :: status
INTEGER, OPTIONAL, INTENT(OUT) :: ierror
```
* [x] not a problem, see comments below

**Comment by wesbland** [comment] 2020-12-03 14:03
Additional comments from @cniethammer:

(using printed page numbers from mpi40-rc-nov-20.pdf)

- [ ] page 898-899 (line 48-1): widow/orphan control
- [ ] page 899 (line 21): MPI_File_type_extend_c() defined using MPI_Count - MPI_Aint is arlready used in the corresponding MPI_File_type_extend() here!?
- [ ] page 899 (line 27): minor irritiation, as sometimes _c functions are not grouped together with the non _c versions due to the alphabetic ordering ... However, I'd leave this as is
- [ ] page 902-903 (line 48-1): widow/orphan control
- [ ] page 905-906 (line 48-1): widow/orphan control
- [ ] page 906-907 (line 48-1): widow/orphan control
- [ ] page 907 (line 1): no _c variant here? The call relies on MPI_COUNT, description includes some hints around overflow. Should state maybe that this is a large count function only?!


Note: I am not a Fortran expert so I may not catch issues with the interfaces in A.4

- [ ] Overall hard to read due to the large count variant, that are grouped together with the same names
- [ ] page 911 (line 1): widow/orphan control

**Comment by hritzdorf** [comment] 2020-12-03 14:37
for 3)

It is correct that "status" doesn't have an intent, since "status" may be MPI_STATUS_IGNORE which is a special predefined variable of Type MPI_Status in Fortran 08.

ASYNCHRONOUS is not specified since MPI_File_read() is a blocking function and asynchronous change of the buffer "buf" is not issued by MPI_File_read() after the end of this function.

An intent OUT is not specified for Fortran, since parts of the buffer "buf" may not be written by MPI_File_read() (for example for a MPI derived datatype). These parts might be lost after end of MPI_File_read() if INTENT(OUT) would be specified.  

for 1:
It is correct. These 2 variants are for overloading of the same MPI function name in Fortran.

Hubert

**Comment by wgropp** [comment] 2020-12-03 20:32
There are ways to address the "widow/orphan" issues mentioned above, but I don't see the value in doing so. In these cases, it just leaves a blank line or so at the bottom of the page, but in some of the other bindings, it could result in significant whitespace (if you want to keep the entire declaration together). If you just want to avoid a widow/orphan (single line at bottom/top of page), while that makes sense for text, its utility for code is lower, and this is a harder fix.

**Comment by wesbland** [comment] 2020-12-04 14:17
From @AOA-Mohammed (pages are PDF pages, not Standard pages):

- [ ] A general comment about any function that contain xx_FN. The two letters seem to be strange little bit like being in different text font.
Examples:
Page 885 lines 29 and 35
page 887 lines 28, 31, and 34
page 898 line 44 and 47
page 907 line 14
- [ ] I noticed that all the functions for BigCount that ends with _c comes directly after the corresponding functions that are not for BigCount. This systematic sort complies with the alphabetical sort which I believe it is there except for a few examples (bindings for one-sided communication)
example
in page 896: line 6  MPI_Get_c comes after MPI_Get_accumulate not after MPI_Get
in page 897 the same case happens for MPI_Rget_c and MPI_Rget
- [ ] In the deprecated C bindings, page 907 some functions are repeated in other binding Is it Ok?
for example lines17 and 19
MPI_Info_get already exists in info object  C bindings  (page 893, line 47)
MPI_Info_get_valuelen already exists exists in info object  C bindings  (page 894, line 7)

**Comment by wesbland** [comment] 2020-12-04 20:52
More from @cblaas:

- [ ] There are two "bad" line breaks most probably coming from the automatic generation:
1037/997 32-34   new line starts with:   *), IERROR
1038/998  5-6       new line starts with:   *), IERROR

- [ ] Previously in MPI-3.1 all MPI procedures and MPI datatypes were links, and now in MPI-4.0 the links are no longer there :(
I assume this comes from the automatic generation... and we will just keep it as it is now.

**Comment by cblaas** [comment] 2020-12-04 23:49
MPI_Register_datarep​
There is no INTENT for dtype_file_extent_fn - is this okay or do we need an INTENT here?
See 1033/993 17 + 26 (Annex A)  =  731/691 42 + 732/692 3 (Chapter 14)

**Comment by cblaas** [comment] 2020-12-05 00:19
In the chapters both with C and with Fortran 2008 bindings we have a fixed order (done consistently):
first small count similar to MPI-3.1, e.g. INTEGER .... count
second big count new in MPI-4.0, e.g. INTEGER(KIND=MPI_COUNT_KIND) ... count

However, in the Annex A the order seems to vary, at least concerning the Fortran 2008 bindings:

e.g. 1015/975 MPI_Rget:
first the big count way at line 5 INTEGER(KIND=MPI_COUNT_KIND) ... origin_count, target_count
second the old MPI-3.1 way at line 17 INTEGER ... origin_count, target_rank, target_count
(this is the other way round as compared to Chapter 12 617/577)

e.g. 1017/977 MPI_Win_create:
first the old MPI-3.1 way at line 30: INTEGER, INTENT(IN) ... disp_unit
second the big count way at line 38: INTEGER(KIND=MPI_ADDRESS_KIND) ... disp_unit
(this is the same order as in Chapter 12 583/543)

Should we care about this order in the Annex A?

**Comment by RolfRabenseifner** [comment] 2020-12-05 10:45
From @cblaas 
> MPI_Register_datarep​
> There is no INTENT for dtype_file_extent_fn - is this okay or do we need an INTENT here?
> See 1033/993 17 + 26 (Annex A) = 731/691 42 + 732/692 3 (Chapter 14)

The problem is harder: All PROCEDURE ...._fn declarations with the exception of dtype_file_extent_fn in mpi_f08 MPI_Register_datarep has changed from no INTENT to INTENT(IN).
I'm not sure whether this was ever discussed with the Fortran specialist, because the rules behind INTENT in mpi_f08 are
 - no INTENT if no win from it
 - no INTENT(OUT) if arrays may be involved that are not totally written in any case
 - no INTENT or INTENT changes if the outcome for API and ABI are not fully clear

Based on this, we never did INTENT for PROCEDURE arguments.
Therefore, I expect, we should revert all the INTENT(IN) for PROCEDURE arguments before releasing MPI-4.0.

**Comment by RolfRabenseifner** [comment] 2020-12-09 10:54
> From @AOA-Mohammed (pages are PDF pages, not Standard pages):
> 
> * [ ]  A general comment about any function that contain xx_FN. The two letters seem to be strange little bit like being in different text font.
>   Examples:
>   Page 885 lines 29 and 35 ...

If you zoom the pdf to 150% then you'll see that all is correct. It is an artifact of Acrobat and may go away after the first large zooming.

**Comment by wesbland** [comment] 2021-01-08 16:04
@RolfRabenseifner This needs an update from #405

**Comment by RolfRabenseifner** [comment] 2021-01-13 18:55
I keep this issue open, because it has a few issues that are unresolved. All other are resolved by Issue #405.

**Comment by RolfRabenseifner** [comment] 2021-01-13 19:05
> From @cniethammer Note: I am not a Fortran expert so I may not catch issues with the interfaces in A.4
> - [ ] Overall hard to read due to the large count variant, that are grouped together with the same names

Proposal: wie mark all larg count Fortran bindinmgs with an additional comment, e.g., with "!(_c)"

> MPI_Bsend(buf, count, datatype, dest, tag, comm, ierror) !(_c)
>   TYPE(*), DIMENSION(..), INTENT(IN) :: buf
>   INTEGER(KIND=MPI_COUNT_KIND), INTENT(IN) :: count
>   TYPE(MPI_Datatype), INTENT(IN) :: datatype
>   INTEGER, INTENT(IN) :: dest, tag
>   TYPE(MPI_Comm), INTENT(IN) :: comm
>   INTEGER, OPTIONAL, INTENT(OUT) :: ierror

This may additionally imply that in A.4, the _c variant is sorted after the normal variant.

**Comment by puribangalore** [comment] 2021-01-14 15:52
If adding !(_c) does not cause any other problem anywhere else, I am good with this change. Surely this will help with the functions in Appendix being sorted, which is a good thing.

**Comment by wesbland** [comment] 2021-01-14 17:37
Is this still being worked for 4.0? Are there existing PRs to cover this? Should we move the rest of this out to 4.1?

**Comment by puribangalore** [comment] 2021-01-14 17:48
@RolfRabenseifner has a proposal to fix this.

**Comment by RolfRabenseifner** [comment] 2021-01-14 19:54
After Puri's approval I'll try to find the technical solution and shall file it into a PR for MPI-4.0.And then I'll ask for more reviews.

**Comment by hritzdorf** [comment] 2021-01-14 19:55
I'm fine with adding the !(_c). However, you need an additional sentence in the beginning of Appendix A4 which explains this. Otherwise, non MPI Forum members will have problems to understand this.

**Comment by RolfRabenseifner** [comment] 2021-01-14 21:21
Yes Hubert, we need it at least two times, because it is also used in all embiggened bindings in the normal chapter, see 
[mpi40-report_Issue405_PR499_v01.pdf](https://github.com/mpi-forum/mpi-issues/files/5817055/mpi40-report_Issue405_PR499_v01.pdf)

**Comment by RolfRabenseifner** [comment] 2021-01-14 23:00
2nd version of the pdf including also the notes in Sections 2.6.2 and 19.2: 
[mpi40-report_Issue405_PR499_v02.pdf](https://github.com/mpi-forum/mpi-issues/files/5817414/mpi40-report_Issue405_PR499_v02.pdf)

**Comment by RolfRabenseifner** [comment] 2021-01-15 07:34
After resolving Martin Ruefennacht's request: 
[mpi40-report_Issue405_PR499_v03.pdf](https://github.com/mpi-forum/mpi-issues/files/5818959/mpi40-report_Issue405_PR499_v03.pdf)

**Comment by RolfRabenseifner** [comment] 2021-01-15 11:54
After resolving Martin Ruefennacht's 2nd request: [mpi40-report_Issue405_PR499_v04.pdf](https://github.com/mpi-forum/mpi-issues/files/5820284/mpi40-report_Issue405_PR499_v04.pdf)

**Comment by RolfRabenseifner** [comment] 2021-01-15 16:42
Next version after Dan's change of ``!(_c)'' into \code{!(_c)} : 
[mpi40-report_Issue405_PR499_v05.pdf](https://github.com/mpi-forum/mpi-issues/files/5821781/mpi40-report_Issue405_PR499_v05.pdf)

**Comment by RolfRabenseifner** [comment] 2021-01-16 22:09
Next version after keeping the quotes and adding two general index entries: 
[mpi40-report_Issue405_PR499_v07.pdf](https://github.com/mpi-forum/mpi-issues/files/5825200/mpi40-report_Issue405_PR499_v07.pdf)

**Comment by RolfRabenseifner** [comment] 2021-01-17 08:46
> More from @cblaas:
> 
> * [ ]  There are two "bad" line breaks most probably coming from the automatic generation:
>   1037/997 32-34   new line starts with:   *), IERROR
>   1038/998  5-6       new line starts with:   *), IERROR
> 
> Answer by @RolfRabenseifner: this problem exists also in the man chapters, i.e., onn p74:28 and p75:28, but only at the old-style Fortran bindings of these two routines MPI_Waitall and MPI_Testall.
> Nevertheless, it should be easy to fix it, by setting Fortran arguments in \mbox.

@cblaas @martinruefenacht I'll check, how to do this. It should be easy to fix in bindingf08.py and bindingf90.py
We should do such a general soltion, because also future APIs may have multi-dimensional array arguments.

**Comment by martinruefenacht** [comment] 2021-01-17 13:04
> [mpi40-report_Issue405_PR499_v07.pdf](https://github.com/mpi-forum/mpi-issues/files/5825200/mpi40-report_Issue405_PR499_v07.pdf)

I cannot find these problems in this PDF?

Latex is exclusively in charge of formatting, the Pythonization has responsibility of the content. The only thing we could do is put some things in mbox environments to prevent breaking longer names or things that should not be split ever, for example C parameters names is a case where we used this fix.

**Comment by RolfRabenseifner** [comment] 2021-01-17 14:15
All ``_c'' in \code{...} - latest pdf of PR499: mpi40-report_Issue405_PR499_v09.pdf

**Comment by RolfRabenseifner** [comment] 2021-01-17 14:28
In [mpi40-report_Issue405_PR499_v09.pdf](https://github.com/mpi-forum/mpi-issues/files/5825747/mpi40-report_Issue405_PR499_v09.pdf) (all page numbers = the visible printed numbers):
- TESTALL: page 77 line 23 and identical page 1006 line 37
- WAITALL: page 76 line 20 and identical page 1007 line 6

There are also other 2-D-arrays (in f08 and f90), e.g.:
- MPI_COMM_SPAWN_MULTIPLE, page 525, line 38 and page 526 line 3

Only by good luck, the parameter(dim1, dim2) is not line-broken at the space between dim1 and dim2

As far as I understand, the problem exists only for 2-D arrays.
This means, in that case, it should be better formatted with  \mbox{parameter(dim1, dim2)}

But my understanding is, that the same formatting would come out, if we would put all parameters in f08 and f90 into such \mbox{ ... }

**Comment by RolfRabenseifner** [comment] 2021-01-17 15:05
@martinruefenacht  Please, can you do a proposal in a new pull request. It should not be part of 499, because PR499 should be finally reviewed and merged.

**Comment by martinruefenacht** [comment] 2021-01-17 21:09
I see what the problem is now with MPI_TESTALL. Yes, I think that is an appropriate use of mbox from Pythonization, since it should be an unbreakable string of characters due to the language model (Fortran). I'll work on a PR for @wgropp to review.

**Comment by RolfRabenseifner** [comment] 2021-01-19 07:18
@martinruefenacht is currently fixing this MPI_TESTALL / MPI_WAITALL, or in general the "\mbox for Fortran arguments" problem in https://github.com/mpi-forum/mpi-standard/pull/500

**Comment by RolfRabenseifner** [comment] 2021-01-19 17:50
The MPI_TESTALL / MPI_WAITALL problem is now resolved. 
This issue can be closed as soon as PR https://github.com/mpi-forum/mpi-standard/pull/500 is merged.

**Comment by RolfRabenseifner** [comment] 2021-01-19 18:41
All topics are done

**Closed by RolfRabenseifner** 2021-01-19 18:41 UTC
Labels: Chapter Committee Change, chap-bindings, mpi-4.0
