### ISSUE TITLE
Update: Section 11.5 - p. 466 - PSCW Fonts

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#209] opened 2020-02-19 22:17 UTC
## Problem

Review font choice for post, start, complete, wait.  Should these be mpicode?

### Suggested Fix

use \mpicode for post/start/complete/wait

**Comment by wesbland** [comment] 2020-04-07 17:56
* Editor - 6
* Chapter committee - 1
* Errata - 0
* Full Proposal - 0

Either way, this goes to @wgropp.

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-04-08 09:50
@wgropp does this mean that "send" and "receive" should be in \mpicode within the point-to-point chapter (also all other 'special' words)? Why are these four words special? In general, "post" is not valid code in most languages (unless it is the name of a variable in the current scope). If we are referring to \mpicode{MPI\_WIN\_POST} when we write "post" then maybe we should use the full LIS procedure name instead of a short-hand? If "post" et al are terms, then they should be defined in chapter 2 and indexed.

**Comment by wgropp** [comment] 2020-04-08 12:38
The issue is that \texttt font is used in the RMA chapter for these. This seems like the wrong choice, as these are not code.  Should they be language independent names (hence the \mpicode suggestion)? Or just text font?

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-04-08 14:49
@wgropp I think we are agreeing here. IMHO, we are both stating that the options are:
1. change "\texttt{post|start|complete|wait}" to "\mpicode{MPI\_WIN\_POST|MPI\_WIN\_START|MPI\_WIN\_COMPLETE|MPI\_WIN\_WAIT}"
2. change "\texttt{post|start|complete|wait}" to "post|start|complete|wait"

I think I favour option 1, primarily because "post|start|complete|wait" are all potentially ambiguous words.
* The word "wait" could mean "\mpicode{MPI\_WAIT}") but "\mpicode{MPI\_WIN\_WAIT}" cannot.
* The word "start" could mean "\mpicode{MPI\_START}" but "\mpicode{MPI\_WIN\_START}" cannot.
* The word "complete" could be confused with any procedure that is used to guarantee completion elsewhere, e.g. "\mpicode{MPI\_WAIT}" or "\mpicode{MPI\_TEST}".
* The word "post" could be confused with different usage elsewhere, e.g. in the sense of "posting an operation".

**Comment by devreal** [comment] 2020-04-14 14:30
I think replacing `post|start|complete|wait` with `MPI_WIN_POST|MPI_WIN_START|MPI_WIN_COMPLETE|MPI_WIN_WAIT` would make reading pages 466-467 much harder. On pages 466-467, the text references to figures 11.2-11.5, which use `post|start|complete|wait` as operation names. Removing the typewriter font would make the use of these terms less clear. At this point, the actual procedures are also not yet defined. On page 467, `put` and `get` are also set in typewriter font in reference to figure 11.4. I would argue to keep it the way it is since those are references to figures explaining the concepts.

AFAICS, the last place these terms are used in typewriter font is on page 469, where they can probably be replaced by their function names. There is some use of the terms in regular font but given the context of chapter 11.5 that should not be ambiguous.

**Comment by wgropp** [comment] 2021-01-07 20:50
I'm going to close this - there's no consensus about the choice, and the current choice provides clarity.

**Closed by wgropp** 2021-01-07 20:50 UTC
Labels: editor change, editor pass, mpi-4.0, wg-rma
