### ISSUE TITLE
Consistency: Figures 8.4 - 8.7 are actually examples

### ISSUE THREAD

**Issue by devreal** [mpi-forum/mpi-issues#395] opened 2020-12-10 13:08 UTC
# Problem

Figures 8.4 - 8.7 consist entirely of code and are situated in "Section 8.9 An Application Example". The use of the figure environment leads to some weird spacing issues. The content appears to be usage examples of topologies and these figures are never referenced anywhere.

# Proposal

Put the code into example environments instead.

# Impact on Implementations

None

# Impact on Users

Better indexing of used routines.

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-12-10 13:46
This code *is* in an example environment already - Example 8.11 - the figures are within that environment.

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-12-10 13:48
An alternative formatting option would be to split the one Example 8.11 into 4 separate examples, with meaningful titles and cross-referencing text that shows how they link together and rely on each other.

**Comment by devreal** [comment] 2020-12-10 13:50
> This code is in an example environment already - Example 8.11 - the figures are within that environment.

The example ends right before these figures:
https://github.com/mpi-forum/mpi-standard/blob/mpi-4.x/chap-topol/topol.tex#L3236

> An alternative formatting option would be to split the one Example 8.11 into 4 separate examples, with meaningful titles and cross-referencing text that shows how they link together and rely on each other.

I believe that would be the cleaner option.

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-12-10 13:51
Duplicate of part of https://github.com/mpi-forum/mpi-issues/issues/229

**Comment by cniethammer** [comment] 2020-12-10 15:01
The example is an entire application sketch with different parts, which are currently placed after the example description into separate figure environments, which have also captions that are too long for the index ...

So I thinkg the way to go should be in-lining the code into the example environment removing the figures but keeping captions as descriptive text.

**Comment by RolfRabenseifner** [comment] 2021-01-13 19:45
The answer is easy: 
> Figures 8.4 - 8.7 consist entirely of code and are situated in "Section 8.9 An Application Example". The use of the figure environment leads to some weird spacing issues. The content appears to be usage examples of topologies and these figures are never referenced anywhere.

The three figures are referenced on page 437 line 46 as part of Example 8.11.
Therefore, the text is correct, although the formatting may be improved.

Therefore, at least for MPI-4.0, resolved.

**Closed by RolfRabenseifner** 2021-01-13 19:45 UTC
Labels: Chapter Committee Change, chap-topologies, mpi-4.0
