### ISSUE TITLE
What is "target node"?

### ISSUE THREAD

**Issue by wgropp** [mpi-forum/mpi-issues#570] opened 2022-08-01 15:53 UTC
Section 12.3, page 571 (MPI40) refers to "target node".  This probably should be "target process".  The troublesome text is

> to the target node specified by the win, target_rank pair.

**Comment by devreal** [comment] 2022-10-20 00:57
I believe this will be addressed in https://github.com/mpi-forum/mpi-standard/pull/611.

**Comment by wesbland** [comment] 2022-10-20 14:16
I'm going to go ahead and close this as a duplicate of #407 then and if someone disagrees, they can reopen it.

**Closed as not planned by wesbland** 2022-10-20 14:16 UTC
Labels: wg-rma, [done] mpi-4.1, chap-rma
