### ISSUE TITLE
Partitioned Communication Chapter RC Review Issues

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#347] opened 2020-11-20 13:57 UTC
# Problem

## From @devreal 

- [x] Page 139: - @regrant response: the start..wait loop text is still there as it does iterate but we fixed the other english
  > This means that partitioned communication can lazily negotiate as late as testing for completion of the operation on the first iteration of a partitioned communication start and test or wait operations.

  -> I find the term `iteration` confusing and the following text does not describe an iterative process. Suggest to replace `iteration` with `occurance`. Plus, remove the `a` in `of a partitioned communication start`

- [x] Page 140:
  send-side and receive-sides -> send-side and receive-side

- [x] Page 141 (Example 4.1): @regrant response: the use of the thread init is purposeful
  Calls MPI_INIT_THREAD with MPI_THREAD_SERIALIZED (and aborts if not provided) but the example does not spawn any threads. I suggest to use MPI_INIT to slightly simplify the example.

- [x] Page 142 (MPI_PSEND_INIT, applies to MPI_PRECV_INIT as well):
  initial address of send buffer (choice) (choice)
  -> initial address of send buffer (choice)

- [x] Page 142 (MPI_PSEND_INIT, applies to MPI_PRECV_INIT as well):
  number of elements send per partition: send -> sent (to be consistent with the  rest of the document)

- [x] Page 142 (MPI_PSEND_INIT):
  Why is the `buf` argument to MPI_PSEND_INIT `void *` and not `const void *`? (it is marked as IN)

- [x] Page 143 (MPI_PRECV_INIT):
  dest   rank of destination -> source    rank of source

- [x] Page 144: @regrant response: we find it useful to highlight the differences from persistence here
  Also unlike MPI_RECV_INIT, MPI_PRECV_INIT takes an info argument.

  -> what is the value in stating the obvious here?

- [x] Page 145 (MPI_PREADY_RANGE):
  partition to mark lowest partition ready for transfer -> lowest partition ready for transfer

  partition to mark highest partition ready for transfer -> highest partition ready for transfer

- [x] Page 145:
  "partition_low ,. . ., partition_high" -> "partition_low, . . ., partition_high" (spacing around first comma)

- [x] Page 146 (MPI_PREADY_LIST):
  Why is `array_of_partitions` not marked as `const int*` and why is it marked INOUT? The text does not mention that the call will modify that buffer...

- [x] Page 146:
  A function for probing the partial completion of the receive buffer
  -> A function for probing the partial completion of the received message (the buffer cannot partially complete)

- [x] Page 147 (MPI_PARRIVED):
  The function takes (request, partition, flag) as arguments. Compare with MPI_PREADY, which takes (partition, request) as arguments. This seems inconsistent. Suggest (partition, request, flag) instead.

  The `flag` has type `boolean` in the LIS but should be `logical` to be consistent with similar functions, e.g. MPI_Test*

- [x] Page 147:
  how many equal partitions of a number (count) of datatypes make up...
  -> how many equal partitions of a number (count) of objects of datatype make up...

  We typically do not transfer datatypes, but objects of certain types.

- [x] Page 148: @regrant response: we'll consider this for future but for now repetition is not a bad thing
  The description of the matching order is repeated three times (once for MPI_PSEND_INIT, once for MPI_PRECV_INIT, and here). Maybe once is sufficient?

- [x] Page 148 (Example 4.2, also applies to Examples 4.3 and 4.4):
  `int main( int argc` -> `int main(int argc)` (space after `main(`)

  `MPI_Comm_rank( MPI_COMM_WORLD, &myrank )` -> `MPI_Comm_rank(MPI_COMM_WORLD, &myrank)`

  The block indentation in these examples varies between 1 and 3 spaces, should be made consistent with the rest of the document.

- [x] Examples 4.2 and 4.3:
  The code requests MPI_THREAD_MULTIPLE from MPI_INIT_THREAD but only checks for provided MPI_THREAD_SERIALIZED

- [x] Page 149:
  OpenMP version 4.0 and greater
  -> OpenMP version 4.0 and later

  parallel task producers produce -> parallel tasks produce

- [x] Throughout Chapter 4:
  Oxford comma missing in `communicator, tag and source` (should be `communicator, tag, and source`

- [x] Throughout Chapter 4:
  Examples are missing titles

## Raised by @GuillaumeMercier 

- [x] p. 99. 4.1, Line 30: "For this sequence partitioned" => "For this sequence, partitioned"?
- [x] p. 99, 4.1, Line 39: "having different initialization" => "having a different"? -relates to behavior, so it should be fine.
- [x] p. 99, 4.1, Line 40: "opposed to persistent point-to-point" => "point-to-point communication"?
- [x] p. 99, 4.1, Line 46: "start and test or wait operations" => "operation"? -both start and test or wait, so operations is right
- [x ] p. 100, 4.2, Line 43: Title (Example 4.1) should be on next page? -this is intended example macro behavior
- [x] p. 102, 4.2.1, Line 27: for the "buf" argument, (choice) is written 2 times
- [x] p. 103, 4.2.1, Line 34: for the "buf" argument, (choice) is written 2 times
- [x] p. 107, 4.2.2, Line 23: "partitioned communications" => "communication"? The word communication is singular since this chapter's begining.
- [x] p. 107, 4.2.2, Line 24: why is there a newline after the word "specified"? - intended underfilled box behavior in the spec
- [x] p. 107, 4.2.3, Line 43: "there is no padding in between partitions" => "between them" (the word partitions is already used in the first part of the sentence)
- [x] p. 108, 4.2.3, Lines 1-5: repetition of lines 29-34 on p. 104 => to remove ? - we're leaving repetition for now
- [x] p. 108, 4.3.1, Lines 14-18: inconsistent use of send-side, sending-side, receive-side
- [x] p. 108, 4.3.1, Lines 15-16: "like the previous example" => "like in the previous example", for consistency with the end of the sentence on lines 17-18.

**Comment by regrant** [comment] 2020-12-04 16:14
@devreal and @GuillaumeMercier Thank you very much for your comments, pull request #360 addresses everything with a check box above. The chapter committee reviewed all of the items and while there are a few that we haven't implemented (particularly the repetition notes, and some of the underfilled boxes, which are intended behaviour), we believe that all of your concerns are now addressed. Thank you for your reviews.

**Comment by regrant** [comment] 2020-12-07 17:52
Pull request https://github.com/mpi-forum/mpi-standard/pull/360 was merged and closed this issue.

**Closed by regrant** 2020-12-07 17:52 UTC
Labels: Chapter Committee Change, chap-part, mpi-4.0
