### ISSUE TITLE
Number of supported/active communicators

### ISSUE THREAD

**Issue by dholmes-epcc-ed-ac-uk** [mpi-forum/mpi-issues#317] opened 2020-10-02 14:03 UTC
# Problem

There is no portable way to determine how many communicators are supported by MPI.

# Proposal

Provide a constant, similar in intent to MPI_TAG_UB, which informs the user of the implementation limit on the number of active communicators. In addition, provide a query function that gives a point-in-time view of how many active communicators are in use at the time of the function call.

Additional constants could be added for the number of supported windows and files in MPI. As implementations typically duplicate a communicator for communication related to each window and file, these might need to be one "number of MPI objects" constant? Separate query functions for each type of MPI object would still be helpful.

# Changes to the Text

The constant MPI_COMM_NUM_SUPPORTED shall provide the maximum number of simultaneously active communicators supported by MPI including all from the World Model, the Dynamic Model, and the Sessions Model.

The value for the MPI_COMM_NUM_SUPPORTED constant is implementation-defined but shall be at least 10,000.

The query function MPI_COMM_NUM_ACTIVE shall provide the number of currently active communicators including all from the World Model, the Dynamic Model, and the Sessions Model.

# Impact on Implementations

Implementations would need to provide the new constant and set it (at compile-time or run-time) to the maximum number of communicators supported.

Implementations would need to provide the new query function and return the number of active communicators. Active includes those where MPI_COMM_FREE has been called, but the communicator has not yet actually been destroyed, i.e. a communicator is still active until the resources it used (specifically its context ID, but also including memory and hardware contexts) can be re-used for another communicator. MPI_COMM_DISCONNECT would decrement this count. All communicator creation operations would increment this number.

# Impact on Users

Users would be able to query the number of supported communicators and adjust usage appropriately to maintain portability between MPI library implementations and between systems/environments.

# References

No additional references yet.

**Comment by isubsmith** [comment] 2020-10-02 14:22
Tony and I discussed this at one point as well. I would also support this effort. I looked into it a bit and at least most of the solutions I had had issues with threads. @tonyskjellum

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-02 14:48
I expect (and am willing to accept) threaded race-conditions. The query is not "how many are available?" but "how many are NOT available?" which reduces the chance of a user complaining about inaccuracies.

NB: I would expect that a valid (low quality) implementation would be to increment the active number during communicator creation but never decrement it.

One complication I can think of is the situation where different sessions were provided by different MPI libraries - does the user get a whole new set of context IDs from the other MPI library instance? Does the on-the-wire protocol include a "libraryID" field to differentiate which MPI library instance originated the message? Currently, no - so one constant and single-valued query function(s) are sufficient. In future, perhaps, a per-session constant and query mechanism might be needed? Or, perhaps, the constant is not actually constant - a session creation that causes dlopen of another MPI library instance sets the constant to a substantially larger value and finalising the last session that needs a particular MPI library instance set it to a substantially lower value?

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-02 14:52
I do not want to de-rail/delay MPI-4.0 timeframe discussions with this proposal, but I am happy to include this in the mix of MPI-4.1 topics.

**Comment by pavanbalaji** [comment] 2020-10-02 14:57
@dholmes-epcc-ed-ac-uk  In the current MPI implementations, we would return an error when there are not enough context IDs available (either locally or on other participating processes).  We define this as a noncatastrophic error, although that part can be implementation specific.  If the implementations can always return a "max" amount, instead of the actual currently available number of communicators, would this proposal actually be better than what already exists?

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-02 15:07
@pavanbalaji I contend "yes".

Just after initialisation of MPI an application could discover (without using all available resources in search of an error) which of its possible implementation plans will work in the current setting. The example given is an application that would like to use one communicator per node. On a system with 10k nodes that would need 10k communicators, can I create that many? Why waste time creating 9999 only to get an error from the 10000th? The application may decide "I cannot run with this restriction" or "I should use a different implementation plan that requires fewer communicators". This is akin to the existing "how many tags are available?" query.

This is an actual problem encountered by some MPI applications, which run in some settings, but fail in others.

**Comment by raffenet** [comment] 2020-10-02 15:16
> Just after initialisation of MPI an application could discover (without using all available resources in search of an error) which of its possible implementation plans will work in the current setting. The example given is an application that would like to use one communicator per node. On a system with 10k nodes that would need 10k communicators, can I create that many? Why waste time creating 9999 only to get an error from the 10000th?

I guess it depends on the scheme being used to allocate context ids? Creating 1 communicator per node in a 10000 node job would only decrease the comm limit by 1 using an allocation scheme similar to MPICH. The limit is how many communicators **a particular process** can be a member of, not some global maximum.

**Comment by wgropp** [comment] 2020-10-02 15:17
The problem with this is the same as many that ask about the internals of an implementation - underlying this is a model of the implementation that says that the implementation "must know how many it can create".  But there might be tradeoffs - in fact, this is the reason for the limitations in the number of contexts - they consume resources in the envelope, in the creation of new communicators, and in memory for the communicators. Another option might be to ask whether, at that moment, the implementation believes (memory availability willing) it could create the number of communicators that the application wants - still not a promise, but a HQ implementation would strive to give the user good information.

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-02 15:27
@wgropp Hmm, akin to "how many chunks of 1024 bytes can I allocate in heap memory?"

Right now: (total_memory - used_memory)/1024 = 1,000,000
*begins allocating*
*allocates something else*
*fails before reaching 1,000,000 chunks because, of course *

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-02 15:28
@raffenet a good point - I wasn't certain of that contextID allocation policy, but I also don't know which other MPI processes are members of each of these "per-node" communicators.

**Comment by raffenet** [comment] 2020-10-02 15:39
> @raffenet a good point - I wasn't certain of that contextID allocation policy, but I also don't know which other MPI processes are members of each of these "per-node" communicators.

Sure. I think what I am trying to gather is are we really interested in a theoretical global maximum? I.e. the number of communicators possible to create if every process did `MPI_COMM_DUP(MPI_COMM_SELF)` until they ran out of context ids (num_context_ids * num_procs). Or a per-process max? Maybe a per-group max?

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-02 15:40
Could this be provided via MPI_T variables? I guess CVARS, but I don't know tools well enough to be certain.
This route reduces portability because all MPI_T variables are implementation defined, but then each could expose information that made sense for their own real limits. For example, TOTAL_CONTEXTS and USED_CONTEXTS or AVAILABLE_CONTEXTS? If no contexts are available then communicator creation will fail (absent races, e.g. release of one in between). If one is available, then a possible reason for failure can be discounted (absent races, e.g. use of one in between) but still no guarantee is given.

An application could query the appropriate MPI_T variable early on and decide if plan A has any chance of working; if not, immediately switch to plan B.

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-02 15:44
I think the request is for some practical way to predict (and thereby avoid) an error after some considerable execution time has been used for setup, which is ultimately left incomplete because the job fails.

"Will it all fit in memory?" is a different question to "Is there some (other) limit preventing this plan?"

Suck-it-and-see is an expensive query function - can we do better?

**Comment by wgropp** [comment] 2020-10-02 15:44
Yes, an MPI_T variable might be appropriate here.  Note that the definition of what the variable means is critical - if the implementation uses a different kind of allocation model, the implementation may say "Not applicable".

**Comment by wgropp** [comment] 2020-10-02 15:46
And you are actually asking a slightly easier question: Do I know, in advance, that I don't think this will work? That's an easier question for the implementation to answer than "the user has a model of how I work that doesn't match my internals, and wants to know, in that model that is not valid for my implementation, what the value of my implementation parameter is".

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-02 15:52
Yes, I believe it would be possible for this (type of) application to provide MPI with a sketch of its plan and ask "might this work (with a favourable wind)?"

The answer maybe should not be "yes|no" but an indication of the implications/requirements? For example, "memory used: X MiB; RMA: unavailable; I/O: unavailable; persistent collectives: limited usage" but that would be wild and weird.

**Comment by bosilca** [comment] 2020-10-02 16:30
I am not certain I understand how the local information about the number of possible/active communicators is of any use for application developers. If the only restriction to communicator creation would have been the available memory then this proposal would have some sense. But, creating a communicator has a collective meaning, because in most implementations we need a unique context id for successfully creating a new communicator. Thus as the most critical resource is the number of globally available context ids and their distribution across the subset of processes that will be used to create communicators, any part of that local information would give users an inaccurate and useless information.

The only part that make sense to me is what @pavanbalaji proposed, a high quality implementation will gracefully and consistently fail on communicator creation with a lesser class of error.

**Comment by adrianjhpc** [comment] 2020-10-02 16:39
@raffenet "I guess it depends on the scheme being used to allocate context ids? Creating 1 communicator per node in a 10000 node job would only decrease the comm limit by 1 using an allocation scheme similar to MPICH. The limit is how many communicators a particular process can be a member of, not some global maximum." 

Just for context on this (I had some internal discussions with @dholmes-epcc-ed-ac-uk on this requirement), the issue often comes up when a mpi_comm_world split is done on a 0/1 variable whether you're in the node or not (or indeed whether you're in a specific group regardless if this is node based or not). In that case you end up with a communicator for each split you do, regardless of whether you're going to use it (i.e. you specify 1 to get a communicator for that group or 0 if you're not going to be in that group, but you still get a communicator regardless of your 0 or 1 value, a communicator for those in the group and a communicator for those not in the group). You can free the communicator if you're not going to use it, but often that freeing of a communicator doesn't actually free up the resources.

Now, I realise there are two things wrong with the paragraph, one that I'm complaining about a specific implementation issue (i.e. an MPI implementation that isn't freeing up communicators when you call mpi_comm_free), and there are potentially better ways to create communicators (i.e. if you want one per node you can split on a node name rather than a 0/1 variable).

However, the general "inclusion/exclusion communicator split" pattern is quite a common one, and understanding what level of groups (i.e. communicators) I as a programmer can guarantee will be supported by any MPI implementation would be useful in designing and implementing a program. What is hard is when a code is developed on one system and works fine, but you move to another system/mpi implementation and it fails on a communicator limit. Or likewise, you scale to a larger problem and it runs out of communicators.

I realise there is no magic bullet here, an MPI implementation on a low memory system may only be able to support so many communicators, but at least if I knew that as a programmer I could design around it.

**Comment by cniethammer** [comment] 2020-10-02 17:55
@raffenet : Not sure if I fully understand the application problem from your context description. If an application needs per node communicators they can be created by a single `MPI_Comm_split` call with one color value per node (i.e. an integer representative for the nodename) in MPI < 4.0 and by `MPI_Comm_split_type` using the new guided mode (see issue https://github.com/mpi-forum/mpi-issues/issues/132) in MPI >= 4.0.

**Comment by pavanbalaji** [comment] 2020-10-02 18:15
@adrianjhpc  I'd like to make a few points that might be important for your understanding of how communicators and context IDs work:

1. Communicators rarely are limited by the amount of memory (not impossible, because it depends on how you are creating the communicator, but rare).  The primary resource constraint is the context ID bits, which are limited because MPI implementations want to keep the <context ID, tag, rank> space within some limit where the network hardware or CPU can do message matching efficiently (e.g., 64 bits).  In most implementations, the max number of context IDs is a few thousand.

2. Communicator/context ID allocation is collective.  This is because implementations try to make sure all processes in a communicator share the same context ID.  This is not a strict requirement from the MPI standard, but implementations choose this model for scalability reasons -- having different context IDs on each process would mean that we'll need to maintain an array of context IDs for each communicator created.

3. The above point also means that context ID fragmentation is possible and happens some times on applications that are not careful.  Thus, depending on what processes are involved, a communicator creation might or might not succeed, even if each process has plenty of local context IDs available, because each process has a different set of context IDs available.  Thus, without knowing how you'll create the future communicators and what processes will be involved in each of those future communicator creation calls, the MPI library cannot give you much useful information.

I understand the problem that you are facing, so I don't want to trivialize it.  But in most such applications that we encountered, we were able to restructure the application to not require so many communicators and to make the communicators more symmetric.  Perhaps you could do that for your application?

**Comment by hzhou** [comment] 2020-10-02 18:35
As we realize the collective nature of this issue, maybe a different API proposal may help. How about a collective call, `MPI_Comm_alloc(MPI_Comm comm, int count, int *alloc_id)`? It will collectively allocate a block of future communicator space within the old comm. Internally, we may collectively reserve a block of context id space. The `alloc_id` can be used as info hint when creating new communicators from the reserved space. 

The return of `MPI_Comm_alloc` will tell the application whether it is possible at all to create `count` communicators.

**Comment by raffenet** [comment] 2020-10-02 18:44
> @raffenet : Not sure if I fully understand the application problem from your context description. If an application needs per node communicators they can be created by a single `MPI_Comm_split` call with one color value per node (i.e. an integer representative for the nodename) in MPI < 4.0 and by `MPI_Comm_split_type` using the new guided mode (see issue #132) in MPI >= 4.0.

@cniethammer I am not saying an application cannot create communicators in this way. What I am saying is that splitting a communicator 10000 ways based on node locality only decreases the comm limit of MPI by 1, not 10000.

I think we need to be careful about exposing per-process information to users when its meaning is highly dependent on other processes in a collective communicator allocation. Basically, I am agreeing with what @bosilca and @pavanbalaji have already said better than me 😄 .

**Comment by adrianjhpc** [comment] 2020-10-02 18:57
> 
> 
> @adrianjhpc I'd like to make a few points that might be important for your understanding of how communicators and context IDs work:
> 
>     1. Communicators rarely are limited by the amount of memory (not impossible, because it depends on how you are creating the communicator, but rare).  The primary resource constraint is the context ID bits, which are limited because MPI implementations want to keep the <context ID, tag, rank> space within some limit where the network hardware or CPU can do message matching efficiently (e.g., 64 bits).  In most implementations, the max number of context IDs is a few thousand.
> 
>     2. Communicator/context ID allocation is collective.  This is because implementations try to make sure all processes in a communicator share the same context ID.  This is not a strict requirement from the MPI standard, but implementations choose this model for scalability reasons -- having different context IDs on each process would mean that we'll need to maintain an array of context IDs for each communicator created.
> 
>     3. The above point also means that context ID fragmentation is possible and happens some times on applications that are not careful.  Thus, depending on what processes are involved, a communicator creation might or might not succeed, even if each process has plenty of local context IDs available, because each process has a different set of context IDs available.  Thus, without knowing how you'll create the future communicators and what processes will be involved in each of those future communicator creation calls, the MPI library cannot give you much useful information.
> 
> 
> I understand the problem that you are facing, so I don't want to trivialize it. But in most such applications that we encountered, we were able to restructure the application to not require so many communicators and to make the communicators more symmetric. Perhaps you could do that for your application?

Thank @pavanbalaji, I completely agree, application restructuring/different design can definitely ameliorate these problems, but from my understanding of the standard as it currently is it's not clear that is required (if I set out to write an MPI application) from the standard. So this maybe is a better user education task, but the approach I've described is commonly used and not necessarily outlandish. For me having either; some clear limits in the standard (i.e. implementations will only guarantee to support X communicators) as you have for tags (i.e. MPI_TAG_UB); or have some functions to query such limits as @dholmes-epcc-ed-ac-uk has outlined would at least inform me as a user of MPI what the issue is here.

**Comment by pavanbalaji** [comment] 2020-10-03 16:01
@adrianjhpc   This would certainly be useful if the information that the MPI library provides is close to the true limit.  My point above with fragmentation is that difference between the minimum number of communicators possible and maximum number of communicators possible can be very large.  For example, if the user creates communicators in ways that cause severe fragmentation, the communicator creation calls will end up failing much earlier.

Then the question becomes: what value should the MPI library return?  The minimum?  The maximum?  Something in between?

**Comment by adrianjhpc** [comment] 2020-10-04 20:48
@pavanbalaji 
Ah, great question, apologies I'd not quite digested the implications of the fragmentation. Ok, in that context I'd like to know the minimum number of communicators available based on the current state of fragmentation in the implementation. 

However, I take your point that to do anything sensible with that would probably mean implementing two versions of the functionality reliant on creating new communicators, one that can operate in a low availability environment, and the other that requires more communicators, so at run time the application could chose between based on how many communicators the MPI implementation says are available; but once I've done that why would I ever use the approach that requires more communicators?

I think, in light of the fact that the available communicators could be variable depending on how the program creates them, I'd need to know more about the mechanics of that before deciding if anything would be useful for the applications I have in mind. For instance, even with fragmentation, could all implementations guarantee that regardless of how communicators are created each process can always create something like 1024 communicators? If so that'd be a useful addition to the standard from my perspective. However, if this is very implementation dependent, or system dependent, that's clearly not going to fly...

**Comment by pavanbalaji** [comment] 2020-10-04 22:55
> For instance, even with fragmentation, could all implementations guarantee that regardless of how communicators are created each process can always create something like 1024 communicators?

If the query function is local, isn't the number of guaranteed new communicators always zero?

Irrespective of what the status of the free context IDs on the local process is, it is possible that the other processes in the system have used up all of their context IDs.  We cannot detect this with only local information, so we would have to assume the worst case.  So the next dup of `MPI_COMM_WORLD`, for example, might fail, although the next dup of `MPI_COMM_SELF` might succeed.

**Comment by dholmes-epcc-ed-ac-uk** [comment] 2020-10-05 09:18
@pavanbalaji that would be a very conservative way to implement it - putting as much as emphasis as possible on to "guaranteed" - more than is expected (I guess) by applications and yet still not a certain guarantee (because there are other possible failure reasons/modes).

**Comment by mhoemmen** [comment] 2020-10-05 17:13
Isn't the number of communicators I can create a global thing, that depends in part on how much memory I'm using on each process?  If so, then how is any nonzero number I might get at any time useful?  I'd rather have comm creation fail in a way that doesn't mess up MPI and returns a useful error code.  That would tell me that I need to fall back to a different algorithm.  (Maybe I'm doing algebraic multigrid, and the mesh is weird and makes me split comms badly.  I could recover by backing out all the comms, and reverting to some less comm-intensive but slower algorithm, like one-level domain decomposition.)

**Comment by hjelmn** [comment] 2020-10-05 17:49
@mhoemmen The number of communicators is not global. It is anywhere between local and global. It is global in the sense that a communicator can only be allocated if a CID is available within the group of processes in the new communicator. This can, as Pavan pointed out, be 0 if there is severe fragmentation within the CID space. This is more of an issue with MPICH than it is with Open MPI at this point as Open MPI no longer requires that a CID index be unique within the process group. Not all networks support the new scheme but we are rolling it out for ```pml/ob1``` and OPA. The new scheme uses a 128-bit identifier for a communicator that is only guaranteed to be unique within the group of processes that created the communicator. On the first message between two peers on a communicator they exchange their local indices for the communicator in the communicator array. This allows for fast communication while also fixing the collective nature of CID generation as well as the fragmentation. In Open MPI's case we could do an allreduce on the group to determine the minimum number of free communicator indices there are across the group. We still limit the number of communicators to 2^16-4 (taking away world, self, etc) to allow the index to fit in 16 bits.

**Comment by wgropp** [comment] 2020-10-06 14:52
I’ll say it again - these requests are based on the user having a model of the internals of the implementation - and if that model isn’t an *exact* match, then the implementation *can’t* provide an accurate answer. This is a fundamental problem with these sorts of requests (and they have a history dating back to MPI-1).

Instead, if we do anything here, the user should be asking about what they want to do, not how they think it should be implemented internally.

Bill



William Gropp
Director and Chief Scientist, NCSA
Thomas M. Siebel Chair in Computer Science
University of Illinois Urbana-Champaign

**Comment by adrianjhpc** [comment] 2020-10-06 15:00
My reference for this request would be MPI_TAG_UB. It provides me a guide when programming of what is guaranteed to be supported across implementations. I don't have to care about internally how this is implemented, but I know if I stick within that my program should work and if it doesn't I can raise it as an issue with the implementation developers.

Given MPI provides that kind of reference for programmers, I didn't think having something similar for communicators was outlandish.

**Comment by wgropp** [comment] 2020-10-06 15:05
Not outlandish at all, but in many ways, very different to the implementation. A similar issue comes up with the eager-limit - this seems like a very similar request, but for the same reasons that I note, it also isn't something that all implementations can accurately provide (there was at least one implementation that didn't even have an eager limit, instead using flow control instead of separate rendezvous protocol, and others have dynamically assigned the threshold for scalability).

**Comment by adrianjhpc** [comment] 2020-10-06 15:24
I've no insight into how implementations handle this, so I'm happy (ok not happy, but you know what I mean) to be told this isn't practical. I guess this really comes down to how much the MPI standard body wants to prescribes how implementations do things. Or at least place restrictions/guarantees on how implementations do things.

**Comment by wgropp** [comment] 2020-10-06 16:07
The MPI Forum has been very careful *not* to constrain implementations.  That approach, IMHO, has contributed to the success and longevity of MPI. I know that it makes it harder for applications sometimes (I've wanted some of these internals myself). This is one reason the MPI_T interface doesn't mandate any particular variables - to let the implementation provide the information it has, rather than trying to match someone else's idea of what the implementation is doing. And why I think it is still interesting to focus on what is really needed, rather than how to address that problem within the context of an implementation model.

**Comment by Wee-Free-Scot** [comment] 2022-07-05 17:34
I think this issue should be closed with no change to MPI -- unless someone wants to drive it (e.g. @adrianjhpc).
I'll close it for now and re-open it if someone shouts.

**Closed by Wee-Free-Scot** 2022-07-05 17:34 UTC
Labels: no-wg, chap-environment, mpi-4.1
