### ISSUE TITLE
MPI_Cart_Coords maxdims/ndims mixup missing from MPI 3.1 to MPI 4.0 

### ISSUE THREAD

**Issue by felker** [mpi-forum/mpi-issues#556] opened 2022-07-11 16:01 UTC
# Problem

In the description of the `coords` parameter of this function, the MPI 3.1 standard claims that it returns an integer array of size `ndims`. It should say that the array is of size `maxdims`. 
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1410981/178306550-523a9756-82a1-4bf4-992e-07e682c34d25.png">

This is already fixed in the 4.0 standard:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1410981/178307105-61770124-4c16-41da-bb9d-486104a04252.png">

# Proposal

Simply add the correction to the 3.1 errata: https://www.mpi-forum.org/docs/mpi-3.1/errata-31.pdf

# References and Pull Requests

**Comment by wesbland** [comment] 2022-07-13 14:18
I added the relevant chapter committee here. 

It looks like this was already fixed for MPI 4.0. Should we consider backdating an errata fix for MPI 3.1 and put it in the errata document as suggested?

@wgropp - Happy to hear from you here as well.

**Comment by wgropp** [comment] 2022-07-13 14:28
This is a clear typo - there really isn't any danger of misinterpretation, since there isn't an ndims argument. As such, it does not belong in the errata, which we've restricted to errors that impact interpretation of the standard.  Otherwise, the errata would exceed 1000 pages.

**Comment by wesbland** [comment] 2022-07-13 14:32
Fair enough. Closing.

**Comment by RolfRabenseifner** [comment] 2022-07-13 16:37
It looks like:
- This text change from 3.1 to 4.0 was never voted into the standard.
- ndims is also not part of the definition of the first routine, MPI_CART_RANK.
  It should be expected (of course in both routines) that this argument is inherited from the cartesian communicator handle.
- In MPI-1.1 until MPI-3.1, the behavior of MPI_CART_COORDS for the case that ndims > maxdims is not defined. Options are:
  - An error of error class MPI_ERR_DIMS is returned (which would be my interpretation);
  - no error returned, but only the first maxdims dimensions are returned in array coords.
- For maxdims > ndims, the expectation is, that the last elements of coords are unchanged (or in mpi_f08 filled in with an undefined value [compiler dependent behaviour of INTENT(OUT)])
- If we stay with this unintended change (because the MPI_ERR_DIMS interpretation would be wrong, and implementation would need to be changed and therefore a changelog would have been needed), then we should report what happened.
- If we go back to the old text, then we should also fix the wording that because the unintended word change is of course a bug.
- If this change was intended, then process to that change seems to be wrong and one should find the issue, pull request, reviews and votes.
- And Bill is right when he says that "there isn't an ndims argument". The section intro says:
  "_8.5.5 Topology Inquiry Functions
If a topology has been defined with one of the above functions, then the topology information
can be looked up using inquiry functions._"
  I would have prefered if already in MPI-1.1, the text of these two routines would have referred to "_ndims as defined for the Cartesian communicator_", and not just "_ndims_".

**Comment by RolfRabenseifner** [comment] 2022-07-13 16:39
Is it okay, that I reopen this issue?

**Comment by wesbland** [comment] 2022-07-13 16:52
> Is it okay, that I reopen this issue?

If you don't think the issue should have been closed, reopening it is just fine.

> - This text change from 3.1 to 4.0 was never voted into the standard.

This came in with the changes for Pythonization (https://github.com/mpi-forum/mpi-standard/pull/152/). The text is https://github.com/mpi-forum/mpi-standard/blob/762dafe9f341cabfae86a5580bd72395c6d68bd8/chap-topol/topol.tex#L1166-L1176 with the comment from @jsquyres:

```python
    # JMS MPI-3.1 erroneously stated "...of size ndims..."
    parameter(
        "coords",
        "COORDINATE",
        length="maxdims",
        direction="out",
        desc=(
            "integer array (of size \\mpiarg{maxdims}) containing the "
            "Cartesian coordinates of specified process"
        ),
    )
```

I'll let the chapter committee discuss the technical merit of the change, but I wanted to provide the background data.

**Comment by wgropp** [comment] 2022-07-13 21:08
I think Rolf is raising a separate issue. This issue is about a simple cut-and-paste error in describing the output array coords that was found and corrected during the pythonization of the bindings. Nothing in this fix addresses the issue of the number of dims of the Cartesian topology being greater than maxdims.

**Comment by felker** [comment] 2022-07-13 22:51
@RolfRabenseifner 's concerns were related to how this typo was noticed in my case, specifically regarding the ambiguity with the `ndims` referenced in `MPI_Cart_rank` earlier on the page inherited from the Carteisan communicator. Only by diff'ing with the 4.0 standard was I able to conclude that the `ndims` size of output `coords` referenced in `MPI_Cart_coords` was indeed a typo, but `ndims` size of input `coords` referenced in `MPI_Cart_rank` was not a typo. 

I can edit the original post and/or title to generalize the issue, if desired.

**Comment by wgropp** [comment] 2022-07-13 23:01
Thanks, @felker .  I think the best thing is to create a new, separate issue about Rolf's concern. I think this update is a simple type correction, but one that, as you note, exposes a concern.

**Comment by RolfRabenseifner** [comment] 2022-07-14 07:22
@wesbland Thank you for the historical details.
@jsquyres I expect that your comment _# JMS MPI-3.1 erroneously stated "...of size ndims..."_and 
@wgropp that this is just a typo correction, is not really true. 

The original (MPI-1.1 - MPI3.1) text was
> IN ____ maxdims __ length of vector coords in the calling program (integer)
> OUT __ coords ____ integer array (of size **ndims**) containing the Cartesian coordinates of specified process (array of integers)

It tells 
- that the user of the cal privides an array of size maxdims integers for the output of coords, and
- that the output vector data that is returned has ndims elements.

What was missing, but of course hopefully clear for all readers, he/she must provide a maxdims >= ndims.
It is also never told what happens, if provided maxdims is less than ndims.

If one would have liked to correct the text to make it more readable, would have been to change it to
> IN ____ maxdims __ length of vector coords in the calling program (integer)
> OUT __ coords ____ integer array (of size **ndims**) containing the Cartesian coordinates of specified process (array of **maxdims** integers)

Even better would have been to add something like:
The outcome is unspecified for the case that maxdims is less than ndims.

In my view, the change that came with the Pythonization is an incorrect change because it looks like that this routine has a also a well defined outcome for  the case that maxdims is less than ndims, i.e., that this conflict looks as resolved by changing the specification of coords.

After this discussion is now within this ticket, I expect, that the solution should also be part of this ticket.

I propose:
1. Reverting the change in MPI-4.0, i.e. keeping "integer array (of size **ndims**) containing ..."
2. Adding "maxdims" to the declaration of coords: "(array of **maxdims** integers)"
3. Adding Adding a clarifying sentence as: "The outcome is unspecified for the case that maxdims is less than ndims."
4. Adding an appropriate errata entry in the change-log for MPI-4.0 --> 4.1
5. Adding this also to the published list of erratas for 4.0, because no implementer or user should be guided to change their user application or MPI library imlementation due to this bug during the Pythonization process.

@felker and all: Last question: are there other such possible Pythonization errors?
I.e., changes in the interfaces that never were really thought through in full consequence?

**Comment by wesbland** [comment] 2022-07-18 14:14
So rather than creating a new issue (given that this issue didn't have a PR or anything, let's just change the name and continue the discussion of whether there should or should not be another change here.

@RolfRabenseifner -
> (@)felker and all: Last question: are there other such possible Pythonization errors?
I.e., changes in the interfaces that never were really thought through in full consequence?

Of course there are other possible errors. We spent a lot of time looking over the proposal as a group including having each chapter committee go over their chapters. However, as would be expected, we are busy humans and surely missed some things. I'm not sure there's much we can do about that now...

If there is a change to be made in the context of this discussion, it sounds like it would not be a particularly large one. @RolfRabenseifner, can you make such a PR and we can discuss its merits there?

**Comment by RolfRabenseifner** [comment] 2022-07-20 07:10
> If there is a change to be made in the context of this discussion, it sounds like it would not be a particularly large one. @RolfRabenseifner, can you make such a PR and we can discuss its merits there?

@wesbland I'll ask my colleague @cniethammer because I'm retired and have only marginal time for such technical implementation. But, as you can see, I still try to contribute my knowledge where it may be helpful.

Most of my proposed errata for MPI_Cart_coords is already said:

> 1. Reverting the change in MPI-4.0, i.e. keeping "integer array (of size ndims) containing ..."
> 2. Adding "maxdims" to the declaration of coords: "(array of maxdims integers)"
> 3. Adding Adding a clarifying sentence as: "The outcome is unspecified for the case that maxdims is less than ndims."
> 4. Adding an appropriate errata entry in the change-log for MPI-4.0 --> 4.1
> 5. Adding this also to the published list of erratas for 4.0, because no implementer or user should be guided to change their user application or MPI library imlementation due to this bug during the Pythonization process.

For 4. the change-log entry, I propose:

The unintented change in the specification of argument coords in MPI_CART_COORDS in MPI-4.0 is reverted to the original specification in MPI-1.1 to MPI-3.1. It is clarified that the outcome of this MPI procedure is unspecified for the case that maxdims is less than ndims.

**Comment by RolfRabenseifner** [comment] 2022-07-20 09:22
A closer look reveals that the same maxdims argument is also used in MPI_CART_GET.
The wording there is significantly better:

> OUT __ coords __ coordinates of calling process in Cartesian structure (array of integers)

Therefore, I propose 
- to use in MPI_CART_COORDS a similar wording, and
- to add the sentence "The outcome is unspecified for the case that maxdims is less than ndims." also to the description of MPI_CART_GET.

Here my proposal for coords in MPI_CART_COORDS:
 
> OUT __ coords __ coordinates of the process with the rank \mpiarg{rank}  in Cartesian structure (array of integers)

 instead of MPI-1.1 to 3.1 and 4.0 versions:
> OUT __ coords __ integer array (of size ndims) containing the Cartesian coordinates of specified process (array of integers)
> OUT __ coords __ integer array (of size maxdims) containing the Cartesian coordinates of specified process (array of integers)

Then, the change-log can be:

 The unintented change in the specification of argument coords in MPI_CART_COORDS in MPI-4.0 is reverted to the original meaning in MPI-1.1 to MPI-3.1. It is clarified that the outcome of  MPI_CART_GET and  MPI_CART_COORDS is unspecified for the case that maxdims is less than ndims.

**Comment by cniethammer** [comment] 2022-07-20 13:36
Just started having a look at this:

At first I see the term vector being used in the parameter descriptions instead of array:
> length of vector coords ...

I think array should be used consistently here as the bindings always use array

> length of array coords ...


Regarding the behaviour of MPI libraries for `MPI_Cart_coords` I did some quick test:
In case `maxdims < ndims`
 - Open MPI simply ignores entries for dimensions > maxdims
 - MVAPICH2 will fail with a fatal error

So putting anything other than undefined behaviour into a potential errata will cause problems with MPI libraries. So I agree with adding a note about this.

However I am not sure about the case maxdims > ndims. Should this be undefined behaviour as well as we cannot make any statement about the elements with index `i` for `ndims < i < maxdims` in the Fortran case? So we would require `maxdims = ndims` for backward compatibility!?

**Comment by RolfRabenseifner** [comment] 2022-07-20 15:15
No, the name maxdims means tht it may be larger than ndims. Therefore, I would not say anything about that case.

**Comment by cniethammer** [comment] 2022-09-09 07:07
Added PDF with marked changes in https://github.com/mpi-forum/mpi-standard/pull/690#issuecomment-1241581133

**Comment by wesbland** [comment] 2022-12-07 18:24
This passed an [errata vote](https://mpi-forum.org/meetings/2022/12/votes) on 2022-12-07.

<table>
<tr>
	<td> Yes
	<td> No
	<td> Abstain
<tr>
	<td> 30
	<td> 0
	<td> 3
</table>

**Closed as completed** 2022-12-08 15:06 UTC
Labels: errata, had reading, passed first vote, passed final vote, scheduled reading, chap-topologies, [done] mpi-4.1
